### FOR USE IN PRODUCTION ###

services:
  app:
    image: brandonxu/residue-estimator-model:1.1-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    environment:
      - UID=${UID}
      - GID=${GID}
    user: "${UID}:${GID}"  # Specify the user with UID and GID from environment variables
    stdin_open: true   # Equivalent to `-i`, keeps stdin open
    tty: true          # Equivalent to `-t`, allocates a TTY
    volumes:
      - ./data:/app/data
    working_dir: /app
